### ISSUE TITLE
Worlds not linking

### ISSUE THREAD

**Issue by 12emin34** [Struck713/PerWorldServer#1]
I cannot link worlds, i do everything correct and reload the plugin, nothing... I even restarted the server and still nothing. I did everything as described on the SpigotMC page.

**Comment by Luigi600** [comment]
The latest commit does not include this functionality. However, I forked the project on [GitLab](https://gitlab.com/Luigi600/worldgrouping) and added world grouping (multiple worlds can now share the same chat and TabList). The grouping should represent the linking feature only more extensive. Furthermore, I added 1.18 support, saving and loading the status of the global chat (status is no longer lost after a reboot/reload), support for commands via a console, more permissions, "left" and "joined" messages when switching "groups", send messages in other worlds, bug fixes etc.

I also published it on [Spigot](https://www.spigotmc.org/resources/worldgrouping.100789/)!
