### ISSUE TITLE
Suggestion: PerWorldEconomy

### ISSUE THREAD

**Issue by TheRobLP** [Struck713/PerWorldServer#2]
Pretty self-explenatory. What I think would be nice, and very fitting for the plugin would be a PerWorldEconomy feature to seperate money. What do you guys think?

**Comment by paj1s** [comment]
Doesn't multiverse take care of this?

**Comment by Struck713** [comment]
> Pretty self-explenatory. What I think would be nice, and very fitting for the plugin would be a PerWorldEconomy feature to seperate money. What do you guys think?

Though I do love the idea, this isn't really the area where I am trying to focus this project. The point of PerWorldServer is to separate the chat and tablist per world. I am currently working on a revamp of the plugin that will include an addons system (where other developers can write addons that can be per world). In theory, the PerWorldEconomy could be done with this.
