### ISSUE TITLE
Invisible players

### ISSUE THREAD

**Issue by AvRrS** [Struck713/PerWorldServer#3]
When using this plugin and MultiVerse a player becomes invisible when teleporting between worlds.

**Comment by Luigi600** [comment]
That is the purpose of the plugin. However, I forked the project (on [GitLab](https://gitlab.com/Luigi600/worldgrouping)) and added "left" and "joined" messages. So this is more transparent/obvious. Furthermore, I added world grouping (multiple worlds can now share the same chat and TabList), saving and loading the status of the global chat (status is no longer lost after a reboot/reload), support for commands via a console, more permissions, send messages in other worlds, bug fixes etc.

I also published it on [Spigot](https://www.spigotmc.org/resources/worldgrouping.100789/)!
