### ISSUE TITLE
World grouping

### ISSUE THREAD

**Issue by paj1s** [Struck713/PerWorldServer#5]
I cannot find another plugin which would make the same as this one but it really needs the world group function to work.

**Comment by Luigi600** [comment]
I forked the project on [GitLab](https://gitlab.com/Luigi600/worldgrouping) and added world grouping (multiple worlds can now share the same chat and TabList). Furthermore, I added 1.18 support, saving and loading the status of the global chat (status is no longer lost after a reboot/reload), support for commands via a console, more permissions, "left" and "joined" messages when switching "groups", send messages in other worlds, bug fixes etc.

I also published it on [Spigot](https://www.spigotmc.org/resources/worldgrouping.100789/)!
