### ISSUE TITLE
Outdated, needs 1.17/1.17.1 support

### ISSUE THREAD

**Issue by broimsuperman** [Struck713/PerWorldServer#6]

**Comment by Luigi600** [comment]
I forked the project on [GitLab](https://gitlab.com/Luigi600/worldgrouping) and added 1.18 support! Furthermore, I added world grouping (multiple worlds can now share the same chat and TabList), saving and loading the status of the global chat (status is no longer lost after a reboot/reload), support for commands via a console, more permissions, "left" and "joined" messages when switching "groups", send messages in other worlds, bug fixes etc.

I also published it on [Spigot](https://www.spigotmc.org/resources/worldgrouping.100789/)!
