### ISSUE TITLE
Materials going only to one player

### ISSUE THREAD

**Issue by LoryKiller** [Struck713/PerWorldServer#7]
Iron and gold generators are giving materials to only one players but in hypixel if there are 3 players on a generator it gives 1 piece of iron each one.

**Comment by Struck713** [comment]
> Iron and gold generators are giving materials to only one players but in hypixel if there are 3 players on a generator it gives 1 piece of iron each one.

I don't believe this is an issue with PerWorldServer, this seems to be an issue with another one of your plugins. Hope this helps!
