### ISSUE TITLE
:)

### ISSUE THREAD

**Issue by xmyoard** [Struck713/PerWorldServer#8]
Hello, nice Plugin!!
Can you please add disabled-worlds:
so we can disable and allow the normal tab list in some-worlds :)

**Comment by Struck713** [comment]
> Hello, nice Plugin!! Can you please add disabled-worlds: so we can disable and allow the normal tab list in some-worlds :)

I will be adding this in an update coming soon. Please keep an eye on the [Spigot resource page](https://www.spigotmc.org/resources/perworldserver-per-world-tablist-and-chat-1-8-1-16-4.23989/). I would suggest subscribing to the page so you can see when I post updates.
