### ISSUE TITLE
1.16.5 World Pairing

### ISSUE THREAD

**Issue by KingStarseeker** [Struck713/PerWorldServer#9]
"Secondly, let me talk about the state of the plugin. For this update, I have added 1.16 as a supported version (as many people have asked). In doing so, I have had to remove the world pairing feature. Now do not worry, this is only temporary. It will be back in the next update.... "

Any news (message from 2021)

**Comment by Struck713** [comment]
> "Secondly, let me talk about the state of the plugin. For this update, I have added 1.16 as a supported version (as many people have asked). In doing so, I have had to remove the world pairing feature. Now do not worry, this is only temporary. It will be back in the next update.... "
> 
> Any news (message from 2021)

Yes, I very much have failed to add the features I intended to add a long time ago. I apologize for that. I will be adding these features soon enough though. I am currently working on a revamp of the plugin which will include world pairing, along with several other features that people have been requesting. I plan to have the plugin supporting all of the latest versions of Minecraft.
